cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

cloudmart_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from core import views

handler404 = views.error_404
handler500 = views.error_500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('addresses/', include('addresses.urls')),
    path('inventory/', include('inventory.urls')),
]


# if settings.DEBUG is False:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.homepage, name='home'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<int:pk>/', views.product_detail, name='detail'),
    path('category/<int:category_id>', views.product_list_by_category, name='products_by_category'),
    path('search/', views.search_products, name='search'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.user_logout, name='logout'),
    path('profile/', views.profile, name='profile'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

from products.models import Category

# Create your views here.
"""Landing page when user enters URL to address bar"""
def homepage(request):
    categories = Category.objects.all() # We pass Category object here to register on home page.
    return render(request, 'core/index.html', {'categories': categories})

def error_404(request, exception):
    return render(request, 'core/404.html', status=404)

def error_500(request):
    return render(request, 'core/500.html', status=500)

core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet"href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block extra_css %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" defer></script>
    <script src="{% static 'js/dropdown.js' %}" defer></script>
    <script src="{% static 'js/alert.js' %}" defer></script>
    <title>CloudMart</title>
</head>
<body class="{% block body_class %} base-body {% endblock %}">
    <!-- Alert for inforimg user he/she is logged in -->
    {% if messages %}
    <div id="message-container" class="message-container">
        {% for message in messages %}
        <div class="alert alert-dismissible fade show alert-top-right 
            {% if message.tags == 'success' %}alert-success{% elif message.tags == 'warning' %}alert-warning{% endif %}" 
            role="alert">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
    </div>
    <!-- Alert ends -->
    <header>
        <nav class="navbar">
            <div class="navbar-left">
                <button class="dropdown-btn">
                    Categories <span class="arrow-down"><i class="bi bi-caret-down-fill"></i></span>
                </button>
                <ul class="dropdown-menu">
                    {% for category in categories %}
                    <li>
                        <a href="{% url 'products:products_by_category' category.id %}" class="nav_link">
                            {{ category.name }}
                        </a>
                    </li>
                    {% endfor %}
                    <li>
                        <a href="{% url 'products:product_list' %}" class="nav_link">All Products</a>
                    </li>
                </ul>
            </div>
            <div class="navbar-center">
                <h1 class="brand">
                    <a href="#" class="brand_nav_link">
                        CloudMart
                    </a>
                </h1>
            </div>
            <div class="navbar-right">
                {% if user.is_authenticated %}
                <div class="profile-container">
                    <div class="profile-dropdown">
                        <i class="bi bi-person-circle"></i>
                        <ul class="profile-menu">
                            <li>
                                <a href="{% url 'users:profile' %}">View Profile</a>
                            </li>
                            <li>
                                <a href="{% url 'users:logout' %}">Logout</a>
                            </li>
                        </ul>
                    </div>
                </div>
                {% else %}
                <button class="user-action-btn">
                    <a href="{% url 'users:login' %}" class="nav_link">Login</a>
                </button>
                <button class="user-action-btn">
                    <a href="{% url 'users:register' %}" class="nav_link">Register</a>
                </button>
                {% endif %}
            </div>
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <!-- Bottom navbar for responsive screen -->
    <footer class="bottom-navbar">
        <a href="#home" class="nav-icon">
            <i class="bi bi-house-door">
                <span>Home</span>
            </i>
        </a>
        <a href="#profile" class="nav-icon">
            <i class="bi bi-person">
                <span>Profile</span>
            </i>
        </a>
        <a href="#cart" class="nav-icon">
            <i class="bi bi-cart">
                <span>Cart</span>
            </i>
        </a>
        <a href="#login-register" class="nav-icon">
            <i class="bi bi-list">
                <span>Menu</span>
            </i>
        </a>
    </footer>
</body>
</html>
</head>

core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0"
    >
    {% block extra_css %}
    <link
        rel="stylesheet"
        href="{% static '/css/index.css' %}"
    >
    {% endblock %}
    <title>
        {% block title %}
        Home | CloudMart
        {% endblock %}
    </title>
</head>

{% block body_class %} index-body {% endblock %}
{% block content %}
<div class="home_container">
    <div class="header">
        {% if user.is_authenticated %}
        <h1>Welcome, {{ user.first_name }}</h1>
        {% else %}
        <h1>Welcome, Guest</h1>
        {% endif %}
    </div>

    <div class="searchBox">
        <form action="{% url 'products:search' %}" method="get">
            <input
                class="form-control"
                type="text"
                name="q"
                id="productSearch"
                placeholder="Enter product to search..."
                value="{{ request.GET.q|default:'' }}"
            >
            <button type="submit" class="btn btn-primary">Search</button>
        </form>
    </div>
</div>
{% endblock %}

</html>