cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

cloudmart_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from core import views

handler404 = views.error_404
handler500 = views.error_500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('addresses/', include('addresses.urls')),
    path('inventory/', include('inventory.urls')),
]


# if settings.DEBUG is False:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'

urlpatterns = [
    path('', views.add_product_to_inventory, name='add_product'),
    path('products_list/', views.inventory_products_list, name='product_list'),
]

inventory/models.py
"""
Inventory Products Model. This is accessible only to admins/privileged users.
"""
from django.db import models
from products.models import Category

# Create your models here.
# class Category(models.Model):
#     name = models.CharField(max_length=200)
#     slug = models.SlugField(unique=True)

#     def __str__(self):
#         return self.name
    
#     class Meta:
#         ordering = ['name']
    
class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField(default=0)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to='product_images/',blank=True,null=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    

inventory/forms.py
"""Form for adding products in inventory. This is accessible only to admins/privileged users."""
from django import forms
from .models import Product

class ProductCreateForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = [
            'name',
            'description',
            'slug',
            'category',
            'price',
            'stock',
            'image',
        ]

        widgets = {
            'description': forms.Textarea(attrs={'rows': 4}),
            'price': forms.NumberInput(attrs={'step': '0.01'}),
            'stock': forms.NumberInput(),
        }

inventory/views.py
"""
Inventory Products Views. This is accessible only to admins/privileged users.
"""
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from .forms import ProductCreateForm
from .models import Product

# Create your views here.
"""Display a form to add products in an inventory."""
def add_product_to_inventory(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = ProductCreateForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                messages.success(request, 'Product added to the inventory successfully.')
                return render(request, 'inventory/product_add.html', {'form': form})
            else:
                messages.error(request, 'Something went wrong.')

        else:
            form = ProductCreateForm()

        return render(request, 'inventory/product_add.html', {'form': form})
    else:
        messages.warning(request, 'You must login to proceed')
        return redirect('users:login')

""" Fetch products list from an inventory."""
def inventory_products_list(request):
    if request.user.is_authenticated:
        products = Product.objects.all()
        paginator = Paginator(products, 10)     # Show 10 products per page
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, 'inventory/products_list.html', {'products': page_obj})
    else:
        messages.warning(request, 'You must login to proceed.')
        return redirect('users:login')

inventory/templates/inventory/product_add.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/product_add.css' %}">
    <title>Inventory Management</title>
</head>
<body>
    {% block content %}
    <!-- TODO: Add conditional rendering to Show form only to authenticated users and
    design the page nicely. -->
    <div class="product-container">
        <div class="product-box">
            <h2 class="text-center">Add Products</h2>
            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li class="message text-danger">{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
            <form method="post">
                {% csrf_token %}
                <div class="form-grid">
                    <div>
                        {{ form.name.label_tag }}
                        {{ form.name }}
                    </div>
                    <div>
                        {{ form.description.label_tag }}
                        {{ form.description }}
                    </div>
                    <div>
                        {{ form.slug.label_tag }}
                        {{ form.slug }}
                    </div>
                    <div>
                        {{ form.category.label_tag }}
                        {{ form.category }}
                    </div>
                    <div>
                        {{ form.price.label_tag }}
                        {{ form.price }}
                    </div>
                    <div>
                        {{ form.stock.label_tag }}
                        {{ form.stock }}
                    </div>
                    <div>
                        {{ form.image.label_tag }}
                        {{ form.image }}
                    </div>
                </div>
                <button type="submit" class="btn btn-primary w-100">Submit</button>
            </form>
        </div>
    </div>
    {% endblock %}
</body>
</html>

inventory/templates/inventory/products_list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/inventory_list.css' %}">
    <title>Products List</title>
</head>
<body>
    <div class="container text-center mt-5">
        {% if products %}
        <div class="row justify-content-center">
            {% for product in products %}
            <div class="col-md-6 mb-4">
                <div class="card p-3 shadow-sm">
                    <h2 class="product-name">{{ product.name }}</h2>
                    <p class="product-price">Price: Rs. {{ product.price }}</p>
                    <p class="product-stock">In stock: {{ product.stock }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="pagination mt-4">
            <nav>
                <ul class="pagination justify-content-center">
                    {% if products.has_previous %}
                    <li class="page-item">
                        <a href="?page={{ products.previous_page_number }}" class="page-link" >Previous</a>
                    </li>
                    {% endif %}
                    {% for num in products.paginator.page_range %}
                    <li class="page-item {% if products.number == num %}active{% endif %}">
                        <a href="?page={{ num }}" class="page-link">{{ num }}</a>
                    </li>
                    {% endfor %}
                    {% if products.has_next %}
                    <li class="page-item">
                        <a href="?page={{ products.next_page_number }}" class="page-link">Next</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
        <!-- Conditional rendering if there's nothing in the inventory -->
        {% else %}
        <h1>
            It seems there are no products in the Inventory. 
            <a href="{% url 'inventory:add_product' %}">Add them</a> 
            and you will see those here.
        </h1>
        {% endif %}
    </div> 
</body>
</html>