cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
]

cloudmart_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from core import views

handler404 = views.error_404
handler500 = views.error_500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    path('addresses/', include('addresses.urls')),
    path('inventory/', include('inventory.urls')),
]


# if settings.DEBUG is False:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<int:pk>/', views.product_detail, name='detail'),
    path('category/<int:category_id>', views.product_list_by_category, name='products_by_category'),
    path('search/', views.search_products, name='search'),
]

products/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

# Commented out Product model from this table to check if single table for both pages would work
# class Product(models.Model):
#     category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
#     name = models.CharField(max_length=255)
#     description = models.TextField(blank=True)
#     price = models.DecimalField(max_digits=10, decimal_places=2)
#     stock = models.PositiveIntegerField(default=0)
#     slug = models.SlugField(unique=True)
#     is_active = models.BooleanField(default=True)
#     created_at = models.DateTimeField(auto_now_add=True)

#     def __str__(self):
#         return self.name """

products/views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, get_object_or_404

from inventory.models import Product
from products.models import Category

# Create your views here.

"""List out Products view."""
def product_list(request):
    products = Product.objects.all()
    paginator = Paginator(products, 10)     # Show 10 products per page
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'products/product_list.html', {'products': page_obj})

""" List products by category. """
def product_list_by_category(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    products = Product.objects.filter(category=category)
    return render(request, 'products/product_list.html', {'products': products, 'category': category})

"""Get specific product details."""
def product_detail(request, pk):
    product = Product.objects.get(pk = pk)
    return render(request, "products/product_detail.html", {'product': product})

def search_products(request):
    query = request.GET.get('q', '')    # Get the search query from the request
    products = Product.objects.filter(Q(name__icontains=query) | Q(description__icontains=query)) if query else None
    paginator = Paginator(products, 10) # Paginate the results
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'products/product_results.html', {'products': page_obj, 'query': query})

products/templates/products/product_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css">
    <title>Product detail</title>
</head>
<body>
    <!-- TODO: Make this page nice and interactive. Each product would be shown here. -->
     <div class="container">
        <div class="justify-content-center">
            <h1 class="text-center">{{ product.name }}</h1>
            <p class="text-center">{{ product.description }}</p>
        </div>
     </div>

</body>
</html>

products/templates/products/product_list.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/products_list.css' %}">
    <title>Products List</title>
</head>
<body>
    <!-- TODO: Add "Back to Home" link/button. -->
    <div class="container text-center mt-5">
        {% if products %}
        <div class="row justify-content-center">
            {% for product in products %}
            <div class="col-md-6 mb-4">
                <div class="card p-3 shadow-sm">
                    <h2 class="product-name">{{ product.name }}</h2>
                    <p class="product-price">{{ product.price }}</p>
                    <p class="product-stock">In stock: {{ product.stock }}</p>
                    <a href="{% url 'products:detail' product.id %}" class="btn btn-primary">
                        View details
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="pagination mt-4">
            <nav>
                <ul class="pagination justify-content-center">
                    {% if products.has_previous %}
                    <li class="page-item">
                        <a href="?page={{ products.previous_page_number }}" class="page-link">Previous</a>
                    </li>
                    {% endif %}
                    {% for num in products.paginator.page_range %}
                    <li class="page-item {% if products.number == num %}active{% endif %}">
                        <a href="?page={{ num }}" class="page-link">{{ num }}</a>
                    </li>
                    {% endfor %}
                    {% if products.has_next %}
                    <li class="page-item">
                        <a href="?page={{ products.next_page_number }}" class="page-link">Next</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
        <!-- Condition rendering if there's nothing in Products database. -->
        {% else %}
        <h1>No products available as of now. Check back later.</h1>
        {% endif %}
    </div>
</body>
</html>

products/templates/products/product_results.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/products_list.css' %}">
    <title>Product Search Results</title>
</head>
<body>
    <!-- TODO: Make this page nice and interactive. Products available in inventory 
     will be shown here. Add logic to show searched Products. -->
    <div class="container text-center mt-5">
        {% if query %}
        <h2>Search results for "{{ query }}"</h2>
        {% endif %}
        {% if products %}
        <div class="row justify-content-center">
            {% for product in products %}
            <div class="col-md-6 mb-4">
                <div class="card p-3 shadow-sm">
                    <h2 class="product-name">{{ product.name }}</h2>
                    <p class="product-price">{{ product.price }}</p>
                    <p class="product-stock">In stock: {{ product.stock }}</p>
                    <!-- TODO: Add link that'd redirect user to product details page. -->
                    <a href="{% url 'products:detail' product.id %}" class="btn btn-primary">
                        View details
                    </a>
                </div>
            </div>
            {% endfor %}
        </div>
        <!-- <div class="pagination mt-4">
            <nav>
                <ul class="pagination justify-content-center">
                    {% if products.has_previous %}
                    <li class="page-item">
                        <a href="?q={{ query }}&page={{ products.previous_page_number }}" class="page-link">Previous</a>
                    </li>
                    {% endif %}
                    {% for num in products.paginator.page_range %}
                    <li class="page-item {% if products.number == num %}active{% endif %}">
                        <a href="?q={{ query }}&page={{ num }}" class="page-link">{{ num }}</a>
                    </li>
                    {% endfor %}
                    {% if products.has_next %}
                    <li class="page-item">
                        <a href="?q={{ query }}&page={{ products.next_page_number }}" class="page-link">Next</a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
        </div> -->
        
        <!-- Conditional rendering if no reuslts are returned. -->
        {% else %}
        <h1>No results came up for "{{ query }}". Ensure that you typed correct query.</h1>
        {% endif %}
    </div>
</body>
</html>